# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'GCCart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GCCart
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  

  target 'GCCartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
